// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

var element = React.createElement("div", undefined, "basic element");

function wrapChildren(children) {
  return React.createElement("div", undefined, React.createElement("div", undefined, "wrapper"), children);
}

function BasicElement(Props) {
  return wrapChildren(element);
}

var make = BasicElement;

export {
  element ,
  wrapChildren ,
  make ,
  
}
/* element Not a pure module */
