// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BasicElement from "./components/BasicElement.mjs";

function $$default(param) {
  console.log("日本語");
  console.log("\xe3\x81\xa0\xe3\x82\x81");
  return React.createElement("div", undefined, "日本語", React.createElement(BasicElement.make, {}));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
