// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as BasicElement from "./components/BasicElement.mjs";

function $$default(param) {
  return React.createElement("div", undefined, "BB page", React.createElement(BasicElement.make, {}));
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
